-- MySQL Script generated by MySQL Workbench
-- sex 19 abr 2024 02:16:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE DATABASE db_asset_hub
USE db_asset_hub

-- -----------------------------------------------------
-- Table `mydb`.`tb_passwd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_passwd` (
  `username` TEXT(25) NOT NULL,
  `hash` VARCHAR(45) NOT NULL,
  `enabled` TINYINT NOT NULL,
  PRIMARY KEY (`username`))



-- -----------------------------------------------------
-- Table `mydb`.`tb_ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_ambiente` (
  `ambiente` TEXT(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`ambiente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_orgs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_orgs` (
  `organization` TEXT(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`organization`))



-- -----------------------------------------------------
-- Table `mydb`.`tb_hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_hardware` (
  `hardware` TEXT(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`hardware`))



-- -----------------------------------------------------
-- Table `mydb`.`tb_host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_host` (
  `id` VARCHAR(45) NOT NULL,
  `hostname` VARCHAR(45) NOT NULL,
  `data` JSON NOT NULL,
  `description` VARCHAR(400) NULL,
  `tb_ambiente_ambiente` TEXT(45) NOT NULL,
  `tb_orgs_organization` TEXT(45) NOT NULL,
  `tb_hardware_hardware` TEXT(45) NOT NULL,
  PRIMARY KEY (`id`, `tb_ambiente_ambiente`, `tb_orgs_organization`, `tb_hardware_hardware`),
  INDEX `fk_tb_host_tb_ambiente1_idx` (`tb_ambiente_ambiente` ASC) VISIBLE,
  INDEX `fk_tb_host_tb_orgs1_idx` (`tb_orgs_organization` ASC) VISIBLE,
  INDEX `fk_tb_host_tb_hardware1_idx` (`tb_hardware_hardware` ASC) VISIBLE,
  CONSTRAINT `fk_tb_host_tb_ambiente1`
    FOREIGN KEY (`tb_ambiente_ambiente`)
    REFERENCES `mydb`.`tb_ambiente` (`ambiente`),
  CONSTRAINT `fk_tb_host_tb_orgs1`
    FOREIGN KEY (`tb_orgs_organization`)
    REFERENCES `mydb`.`tb_orgs` (`organization`),
  CONSTRAINT `fk_tb_host_tb_hardware1`
    FOREIGN KEY (`tb_hardware_hardware`)
    REFERENCES `mydb`.`tb_hardware` (`hardware`))

